### PR TITLE
fix line breaks in readme config. file example

### PR DESCRIPTION
**Pull request by olshevskiy87**

### CODE REVIEW

**Comment by timofonic** [comment]
Is this wrong in some way? It's a typo in the README, so not so important :D

**Comment by olshevskiy87** [comment]
> Is this wrong in some way?

@timofonic I think - yes. README (or any other help file) should provide the correct information and examples. You should be able just copy-paste the code and it should work without any syntax errors. At least for such easy code snippet as this one. Don't you think so?

**Comment by KolesnichenkoDS** [comment]
@olshevskiy87 thank you for contributing, but I've already rewritten the plugin so it uses JSON instead of VimL, because I want to write similar plugins for other editors (Sublime Text, Atom, VS Code), so it will be possible to use the same project configuration for several editors.
BTW, current version of plugin doesn't support 'classic' Vim, it only supports NeoVim. So if you use Vim, don't update the plugin for now — soon there will be a version for Vim.

**Comment by olshevskiy87** [comment]
@KolesnichenkoDS ok, I got it

**Pull request closed without merging**
